import { GEOFENCES } from "./geo";
import type {
  Coord,
  Driver,
  FleetAlert,
  FleetSnapshot,
  FuelDay,
  MaintenanceJob,
  Vehicle,
} from "./fleet-types";
import { DEFAULT_SETTINGS } from "./fleet-types";

/** Evening board clock so SSR and the first client paint share identical sample times. */
export const DEMO_NOW = Date.parse("2026-08-19T21:40:00.000-05:00");

function iso(now: number, minutesFromNow: number): string {
  return new Date(now + minutesFromNow * 60_000).toISOString();
}

function day(now: number, daysAgo: number): string {
  const d = new Date(now - daysAgo * 86_400_000);
  return d.toISOString().slice(0, 10);
}

function route(...pairs: [number, number][]): Coord[] {
  return pairs.map(([lat, lng]) => ({ lat, lng }));
}

export function createSeedData(now = DEMO_NOW): FleetSnapshot {
  const drivers: Driver[] = [
    {
      id: "d-maya",
      name: "Maya Ortiz",
      role: "Lead driver",
      phone: "9135550144",
      safetyScore: 96,
      hoursToday: 8.4,
      hoursWeek: 41.2,
      vehicleId: "v-104",
      status: "driving",
      hireYear: 2019,
      speeding30d: 0,
      idleEvents30d: 2,
      harsh30d: 0,
    },
    {
      id: "d-cole",
      name: "Cole Brennan",
      role: "Linehaul",
      phone: "8165550190",
      safetyScore: 64,
      hoursToday: 7.1,
      hoursWeek: 38.6,
      vehicleId: "v-402",
      status: "driving",
      hireYear: 2024,
      speeding30d: 6,
      idleEvents30d: 4,
      harsh30d: 5,
    },
    {
      id: "d-priya",
      name: "Priya Shah",
      role: "City route",
      phone: "9135550172",
      safetyScore: 91,
      hoursToday: 6.8,
      hoursWeek: 36.0,
      vehicleId: "v-309",
      status: "driving",
      hireYear: 2021,
      speeding30d: 1,
      idleEvents30d: 1,
      harsh30d: 0,
    },
    {
      id: "d-andres",
      name: "Andres Velez",
      role: "Warehouse",
      phone: "8165550118",
      safetyScore: 88,
      hoursToday: 9.2,
      hoursWeek: 44.5,
      vehicleId: "v-118",
      status: "on_shift",
      hireYear: 2018,
      speeding30d: 0,
      idleEvents30d: 7,
      harsh30d: 1,
    },
    {
      id: "d-nyla",
      name: "Nyla Brooks",
      role: "Airport run",
      phone: "8165550166",
      safetyScore: 93,
      hoursToday: 5.5,
      hoursWeek: 29.4,
      vehicleId: "v-415",
      status: "driving",
      hireYear: 2022,
      speeding30d: 0,
      idleEvents30d: 0,
      harsh30d: 0,
    },
    {
      id: "d-jonah",
      name: "Jonah Peck",
      role: "Field tech",
      phone: "9135550121",
      safetyScore: 84,
      hoursToday: 7.6,
      hoursWeek: 39.1,
      vehicleId: "v-601",
      status: "break",
      hireYear: 2020,
      speeding30d: 2,
      idleEvents30d: 3,
      harsh30d: 2,
    },
    {
      id: "d-elena",
      name: "Elena Cho",
      role: "Shuttle",
      phone: "8165550133",
      safetyScore: 97,
      hoursToday: 4.2,
      hoursWeek: 22.8,
      vehicleId: "v-221",
      status: "on_shift",
      hireYear: 2017,
      speeding30d: 0,
      idleEvents30d: 1,
      harsh30d: 0,
    },
    {
      id: "d-marcus",
      name: "Marcus Hale",
      role: "City route",
      phone: "9135550188",
      safetyScore: 79,
      hoursToday: 8.0,
      hoursWeek: 40.3,
      vehicleId: "v-512",
      status: "driving",
      hireYear: 2023,
      speeding30d: 3,
      idleEvents30d: 2,
      harsh30d: 1,
    },
    {
      id: "d-ruth",
      name: "Ruth Klein",
      role: "South loop",
      phone: "8165550149",
      safetyScore: 90,
      hoursToday: 6.1,
      hoursWeek: 33.7,
      vehicleId: "v-703",
      status: "driving",
      hireYear: 2016,
      speeding30d: 1,
      idleEvents30d: 0,
      harsh30d: 0,
    },
    {
      id: "d-devon",
      name: "Devon Price",
      role: "Relief",
      phone: "9135550107",
      safetyScore: 86,
      hoursToday: 0,
      hoursWeek: 18.4,
      vehicleId: null,
      status: "off",
      hireYear: 2025,
      speeding30d: 0,
      idleEvents30d: 0,
      harsh30d: 0,
    },
  ];

  const vehicles: Vehicle[] = [
    {
      id: "v-104",
      unit: "CW-104",
      name: "East linehaul",
      make: "Freightliner",
      model: "M2 106",
      year: 2022,
      vin: "1FVACWDT8NH123401",
      plate: "CW 104",
      class: "box",
      status: "moving",
      lat: 39.103,
      lng: -94.52,
      heading: 90,
      speedMph: 54,
      odometer: 87420,
      fuelPct: 62,
      driverId: "d-maya",
      lastPingAt: iso(now, -1),
      idleMinutes: 0,
      route: route(
        [39.1, -94.73],
        [39.103, -94.58],
        [39.1, -94.48],
        [39.094, -94.38],
        [39.091, -94.34],
      ),
      routeT: 0.42,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.78,
      mpg: 9.4,
      nextPmMiles: 2580,
      assignedSince: iso(now, -410),
    },
    {
      id: "v-118",
      unit: "CW-118",
      name: "Warehouse van",
      make: "Ford",
      model: "Transit 250",
      year: 2021,
      vin: "1FTBR1C85MKA44118",
      plate: "CW 118",
      class: "van",
      status: "idle",
      lat: 39.091,
      lng: -94.415,
      heading: 12,
      speedMph: 0,
      odometer: 61204,
      fuelPct: 48,
      driverId: "d-andres",
      lastPingAt: iso(now, -2),
      idleMinutes: 41,
      route: route([39.091, -94.415], [39.091, -94.415]),
      routeT: 0,
      faultCode: null,
      geofenceId: "gf-wh",
      utilization7d: 0.54,
      mpg: 16.2,
      nextPmMiles: 840,
      assignedSince: iso(now, -520),
    },
    {
      id: "v-207",
      unit: "CW-207",
      name: "Utility 07",
      make: "Ram",
      model: "2500",
      year: 2020,
      vin: "3C6UR5CJ0LG322207",
      plate: "CW 207",
      class: "utility",
      status: "in_shop",
      lat: 38.9536,
      lng: -94.7336,
      heading: 0,
      speedMph: 0,
      odometer: 118330,
      fuelPct: 31,
      driverId: null,
      lastPingAt: iso(now, -18),
      idleMinutes: 0,
      route: route([38.9536, -94.7336]),
      routeT: 0,
      faultCode: "P0420",
      geofenceId: "gf-yard",
      utilization7d: 0.41,
      mpg: 14.8,
      nextPmMiles: -120,
      assignedSince: null,
    },
    {
      id: "v-221",
      unit: "CW-221",
      name: "Crew shuttle",
      make: "Chevrolet",
      model: "Express 3500",
      year: 2023,
      vin: "1GAZGPFG3P1128221",
      plate: "CW 221",
      class: "shuttle",
      status: "on_lot",
      lat: 38.955,
      lng: -94.731,
      heading: 270,
      speedMph: 0,
      odometer: 28410,
      fuelPct: 88,
      driverId: "d-elena",
      lastPingAt: iso(now, -3),
      idleMinutes: 12,
      route: route([38.955, -94.731]),
      routeT: 0,
      faultCode: null,
      geofenceId: "gf-yard",
      utilization7d: 0.33,
      mpg: 12.1,
      nextPmMiles: 4120,
      assignedSince: iso(now, -180),
    },
    {
      id: "v-309",
      unit: "CW-309",
      name: "South loop",
      make: "Ford",
      model: "Transit 350",
      year: 2024,
      vin: "1FTBR3X8XRKA55309",
      plate: "CW 309",
      class: "van",
      status: "moving",
      lat: 38.96,
      lng: -94.668,
      heading: 180,
      speedMph: 42,
      odometer: 19680,
      fuelPct: 71,
      driverId: "d-priya",
      lastPingAt: iso(now, -1),
      idleMinutes: 0,
      route: route(
        [39.04, -94.64],
        [38.98, -94.668],
        [38.9, -94.668],
        [38.86, -94.67],
      ),
      routeT: 0.38,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.81,
      mpg: 17.4,
      nextPmMiles: 5320,
      assignedSince: iso(now, -360),
    },
    {
      id: "v-314",
      unit: "CW-314",
      name: "OP hold",
      make: "Mercedes-Benz",
      model: "Sprinter 2500",
      year: 2022,
      vin: "W1Y4ECHY1NT073314",
      plate: "CW 314",
      class: "van",
      status: "idle",
      lat: 38.982,
      lng: -94.671,
      heading: 40,
      speedMph: 0,
      odometer: 54310,
      fuelPct: 39,
      driverId: null,
      lastPingAt: iso(now, -4),
      idleMinutes: 18,
      route: route([38.982, -94.671]),
      routeT: 0,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.62,
      mpg: 18.0,
      nextPmMiles: 1440,
      assignedSince: null,
    },
    {
      id: "v-402",
      unit: "CW-402",
      name: "Loop box",
      make: "Isuzu",
      model: "NPR-HD",
      year: 2021,
      vin: "JALC4W165M7004402",
      plate: "CW 402",
      class: "box",
      status: "moving",
      lat: 38.9,
      lng: -94.5,
      heading: 250,
      speedMph: 78,
      odometer: 76220,
      fuelPct: 44,
      driverId: "d-cole",
      lastPingAt: iso(now, 0),
      idleMinutes: 0,
      route: route(
        [39.08, -94.36],
        [38.96, -94.38],
        [38.88, -94.5],
        [38.87, -94.64],
        [38.92, -94.78],
      ),
      routeT: 0.48,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.74,
      mpg: 10.1,
      nextPmMiles: 920,
      assignedSince: iso(now, -390),
    },
    {
      id: "v-415",
      unit: "CW-415",
      name: "Airport run",
      make: "Ford",
      model: "F-150",
      year: 2023,
      vin: "1FTFW1E89PFA66415",
      plate: "CW 415",
      class: "pickup",
      status: "moving",
      lat: 39.26,
      lng: -94.69,
      heading: 320,
      speedMph: 61,
      odometer: 22140,
      fuelPct: 55,
      driverId: "d-nyla",
      lastPingAt: iso(now, -1),
      idleMinutes: 0,
      route: route(
        [39.11, -94.59],
        [39.16, -94.62],
        [39.22, -94.66],
        [39.28, -94.7],
        [39.297, -94.714],
      ),
      routeT: 0.72,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.58,
      mpg: 19.6,
      nextPmMiles: 3860,
      assignedSince: iso(now, -210),
    },
    {
      id: "v-508",
      unit: "CW-508",
      name: "West parts",
      make: "Ford",
      model: "Transit Connect",
      year: 2019,
      vin: "NM0LS7E29K1372508",
      plate: "CW 508",
      class: "van",
      status: "idle",
      lat: 39.023,
      lng: -94.72,
      heading: 88,
      speedMph: 0,
      odometer: 98450,
      fuelPct: 9,
      driverId: null,
      lastPingAt: iso(now, -6),
      idleMinutes: 9,
      route: route([39.023, -94.72]),
      routeT: 0,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.49,
      mpg: 24.1,
      nextPmMiles: 210,
      assignedSince: null,
    },
    {
      id: "v-512",
      unit: "CW-512",
      name: "Downtown",
      make: "Ram",
      model: "ProMaster 2500",
      year: 2022,
      vin: "3C6LRVDG4NE345512",
      plate: "CW 512",
      class: "van",
      status: "moving",
      lat: 39.1,
      lng: -94.578,
      heading: 20,
      speedMph: 18,
      odometer: 44880,
      fuelPct: 67,
      driverId: "d-marcus",
      lastPingAt: iso(now, -1),
      idleMinutes: 0,
      route: route(
        [39.08, -94.59],
        [39.1, -94.578],
        [39.12, -94.57],
        [39.11, -94.55],
        [39.09, -94.56],
        [39.08, -94.59],
      ),
      routeT: 0.22,
      faultCode: null,
      geofenceId: "gf-dt",
      utilization7d: 0.71,
      mpg: 15.8,
      nextPmMiles: 1980,
      assignedSince: iso(now, -300),
    },
    {
      id: "v-601",
      unit: "CW-601",
      name: "North tech",
      make: "Ford",
      model: "F-250",
      year: 2021,
      vin: "1FT7W2B60MEC22601",
      plate: "CW 601",
      class: "utility",
      status: "idle",
      lat: 39.24,
      lng: -94.65,
      heading: 140,
      speedMph: 0,
      odometer: 67330,
      fuelPct: 52,
      driverId: "d-jonah",
      lastPingAt: iso(now, -3),
      idleMinutes: 27,
      route: route([39.24, -94.65]),
      routeT: 0,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.66,
      mpg: 13.2,
      nextPmMiles: 740,
      assignedSince: iso(now, -440),
    },
    {
      id: "v-618",
      unit: "CW-618",
      name: "Spare transit",
      make: "Ford",
      model: "Transit 250",
      year: 2018,
      vin: "1FTYR2CM5JKB44618",
      plate: "CW 618",
      class: "van",
      status: "offline",
      lat: 38.991,
      lng: -94.634,
      heading: 0,
      speedMph: 0,
      odometer: 142880,
      fuelPct: 22,
      driverId: null,
      lastPingAt: iso(now, -186),
      idleMinutes: 0,
      route: route([38.991, -94.634]),
      routeT: 0,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.12,
      mpg: 15.4,
      nextPmMiles: -640,
      assignedSince: null,
    },
    {
      id: "v-703",
      unit: "CW-703",
      name: "Summit run",
      make: "Mercedes-Benz",
      model: "Sprinter 3500",
      year: 2023,
      vin: "W1Y4ECHY8PT087703",
      plate: "CW 703",
      class: "van",
      status: "moving",
      lat: 38.93,
      lng: -94.4,
      heading: 110,
      speedMph: 46,
      odometer: 31220,
      fuelPct: 58,
      driverId: "d-ruth",
      lastPingAt: iso(now, -1),
      idleMinutes: 0,
      route: route(
        [39.04, -94.5],
        [38.96, -94.42],
        [38.91, -94.39],
        [38.88, -94.36],
      ),
      routeT: 0.55,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.69,
      mpg: 17.9,
      nextPmMiles: 2640,
      assignedSince: iso(now, -250),
    },
    {
      id: "v-720",
      unit: "CW-720",
      name: "Yard spare",
      make: "Ford",
      model: "F-150",
      year: 2024,
      vin: "1FTFW1E82RFA88720",
      plate: "CW 720",
      class: "pickup",
      status: "on_lot",
      lat: 38.952,
      lng: -94.736,
      heading: 180,
      speedMph: 0,
      odometer: 4120,
      fuelPct: 94,
      driverId: null,
      lastPingAt: iso(now, -8),
      idleMinutes: 0,
      route: route([38.952, -94.736]),
      routeT: 0,
      faultCode: null,
      geofenceId: "gf-yard",
      utilization7d: 0.18,
      mpg: 20.4,
      nextPmMiles: 5880,
      assignedSince: null,
    },
    {
      id: "v-804",
      unit: "CW-804",
      name: "West box",
      make: "Hino",
      model: "L6",
      year: 2020,
      vin: "5PVNJ8JV9L4S44804",
      plate: "CW 804",
      class: "box",
      status: "moving",
      lat: 39.04,
      lng: -94.8,
      heading: 10,
      speedMph: 49,
      odometer: 91240,
      fuelPct: 36,
      driverId: null,
      lastPingAt: iso(now, -2),
      idleMinutes: 0,
      route: route(
        [38.92, -94.78],
        [39.04, -94.82],
        [39.14, -94.8],
        [39.22, -94.75],
      ),
      routeT: 0.33,
      faultCode: null,
      geofenceId: null,
      utilization7d: 0.72,
      mpg: 8.8,
      nextPmMiles: 480,
      assignedSince: null,
    },
    {
      id: "v-819",
      unit: "CW-819",
      name: "PM hold",
      make: "Ford",
      model: "Transit 250",
      year: 2019,
      vin: "1FTYR2CM4KKB55819",
      plate: "CW 819",
      class: "van",
      status: "on_lot",
      lat: 38.957,
      lng: -94.729,
      heading: 90,
      speedMph: 0,
      odometer: 126410,
      fuelPct: 41,
      driverId: null,
      lastPingAt: iso(now, -11),
      idleMinutes: 0,
      route: route([38.957, -94.729]),
      routeT: 0,
      faultCode: null,
      geofenceId: "gf-yard",
      utilization7d: 0.22,
      mpg: 16.0,
      nextPmMiles: -410,
      assignedSince: null,
    },
  ];

  const alerts: FleetAlert[] = [
    {
      id: "a-1",
      vehicleId: "v-402",
      kind: "speeding",
      severity: "critical",
      title: "78 mph in a 65",
      detail: "CW-402 on I-435 westbound, south of Independence. Cole Brennan driving. Duration 2 min.",
      at: iso(now, -3),
      acknowledged: false,
    },
    {
      id: "a-2",
      vehicleId: "v-118",
      kind: "idle",
      severity: "warn",
      title: "Idle 41 minutes",
      detail: "CW-118 sitting at East warehouse with engine on. Andres Velez on shift — likely loading, still over the 15 min threshold.",
      at: iso(now, -26),
      acknowledged: false,
    },
    {
      id: "a-3",
      vehicleId: "v-508",
      kind: "fuel",
      severity: "critical",
      title: "Fuel at 9%",
      detail: "CW-508 parked in Shawnee with no driver assigned. Range under 40 miles at current MPG.",
      at: iso(now, -14),
      acknowledged: false,
    },
    {
      id: "a-4",
      vehicleId: "v-207",
      kind: "fault",
      severity: "warn",
      title: "P0420 catalyst efficiency",
      detail: "Logged at check-in this afternoon. Vehicle already in the Lenexa bay for brakes; add cat inspection to the RO.",
      at: iso(now, -96),
      acknowledged: false,
    },
    {
      id: "a-5",
      vehicleId: "v-819",
      kind: "pm",
      severity: "warn",
      title: "PM 410 miles overdue",
      detail: "A-service plus trans fluid. Unit is on the Lenexa lot — pull it before tomorrow's AM dispatch.",
      at: iso(now, -220),
      acknowledged: false,
    },
    {
      id: "a-6",
      vehicleId: "v-804",
      kind: "harsh",
      severity: "warn",
      title: "Harsh braking, K-10",
      detail: "0.62g event westbound near K-10 / I-435. No driver currently assigned to the unit.",
      at: iso(now, -38),
      acknowledged: false,
    },
    {
      id: "a-7",
      vehicleId: "v-618",
      kind: "offline",
      severity: "critical",
      title: "No ping for 3 hours",
      detail: "Last seen Prairie Village. Device battery or ignition-off with tracker asleep. Confirm it isn't on a customer lot.",
      at: iso(now, -170),
      acknowledged: false,
    },
    {
      id: "a-8",
      vehicleId: "v-415",
      kind: "geofence",
      severity: "info",
      title: "Entering MCI airport",
      detail: "Expected: Nyla Brooks on the 9:25 p.m. air-cargo pickup. Fence entry in ~4 minutes at current speed.",
      at: iso(now, -2),
      acknowledged: false,
    },
    {
      id: "a-9",
      vehicleId: "v-314",
      kind: "inspection",
      severity: "info",
      title: "DVIR: cracked mirror",
      detail: "Morning inspection flagged passenger-side mirror housing. Vehicle still in service in Overland Park.",
      at: iso(now, -560),
      acknowledged: true,
    },
    {
      id: "a-10",
      vehicleId: "v-601",
      kind: "idle",
      severity: "info",
      title: "Idle 27 minutes",
      detail: "Northland job site. Jonah Peck on break — within policy if engine-off, currently engine-on.",
      at: iso(now, -12),
      acknowledged: false,
    },
  ];

  const jobs: MaintenanceJob[] = [
    {
      id: "j-1",
      vehicleId: "v-207",
      title: "Front brakes + P0420 inspect",
      shop: "Lenexa bay 2",
      dueAt: iso(now, -40),
      status: "in_progress",
      milesDue: null,
      cost: 840,
    },
    {
      id: "j-2",
      vehicleId: "v-819",
      title: "A-service + trans fluid",
      shop: "Lenexa bay 1",
      dueAt: iso(now, -180),
      status: "overdue",
      milesDue: -410,
      cost: 320,
    },
    {
      id: "j-3",
      vehicleId: "v-618",
      title: "Tracker / battery diagnosis",
      shop: "Mobile",
      dueAt: iso(now, 30),
      status: "due",
      milesDue: null,
      cost: 180,
    },
    {
      id: "j-4",
      vehicleId: "v-508",
      title: "Oil + filter, 98k",
      shop: "Shawnee lube",
      dueAt: iso(now, 90),
      status: "due",
      milesDue: 210,
      cost: 95,
    },
    {
      id: "j-5",
      vehicleId: "v-104",
      title: "DOT annual",
      shop: "Lenexa",
      dueAt: iso(now, 60 * 24 * 6),
      status: "scheduled",
      milesDue: 2580,
      cost: 260,
    },
    {
      id: "j-6",
      vehicleId: "v-402",
      title: "Rear tires (steer OK)",
      shop: "I-435 truck tire",
      dueAt: iso(now, 60 * 18),
      status: "scheduled",
      milesDue: 920,
      cost: 780,
    },
    {
      id: "j-7",
      vehicleId: "v-804",
      title: "DEF system rinse",
      shop: "Lenexa",
      dueAt: iso(now, 60 * 48),
      status: "scheduled",
      milesDue: 480,
      cost: 210,
    },
    {
      id: "j-8",
      vehicleId: "v-221",
      title: "Cabin HVAC recharge",
      shop: "Lenexa",
      dueAt: iso(now, -60 * 24 * 2),
      status: "done",
      milesDue: null,
      cost: 165,
    },
  ];

  const fuel: FuelDay[] = Array.from({ length: 14 }, (_, i) => {
    const ago = 13 - i;
    const base = 118 + Math.round(Math.sin(ago * 0.9) * 14);
    const idleGal = 9 + (ago % 4) * 1.4;
    const gallons = base + (ago === 0 ? -8 : 0);
    return {
      day: day(now, ago),
      gallons,
      cost: Math.round(gallons * 3.62 * 100) / 100,
      idleGal: Math.round(idleGal * 10) / 10,
      miles: Math.round(gallons * 14.2),
    };
  });

  return {
    vehicles,
    drivers,
    alerts,
    jobs,
    fuel,
    geofences: GEOFENCES,
    settings: { ...DEFAULT_SETTINGS },
  };
}
