import type { RepairLine, RepairOrder, TimelineEvent } from "./types";

function iso(now: number, minutesFromNow: number): string {
  return new Date(now + minutesFromNow * 60_000).toISOString();
}

function line(id: string, description: string, amount: number, hours: number, state: RepairLine["state"]): RepairLine {
  return { id, description, amount, hours, state };
}

function ev(id: string, minutesFromNow: number, now: number, label: string, kind: TimelineEvent["kind"]): TimelineEvent {
  return { id, at: iso(now, minutesFromNow), label, kind };
}

/** Mid-day shop clock so SSR and the first client paint share identical sample times. */
export const DEMO_NOW = Date.parse("2026-08-19T14:42:00.000-05:00");

export function createSeedData(now = DEMO_NOW): RepairOrder[] {
  const advisor = "Service Advisor";
  return [
    {
      id: "00000000-0000-4000-8000-000000045281",
      roNumber: "45281",
      customerName: "Elena Martinez",
      customerPhone: "8165550142",
      vehicle: "Camry SE",
      year: 2021,
      mileage: 68440,
      vin: "4T1G11AK5MU548210",
      technician: "Diego Ruiz",
      advisor,
      appointmentTime: iso(now, -215),
      status: "waiting_approval",
      statusChangedAt: iso(now, -38),
      concern: "Customer states a grinding noise from the right-front when braking at low speeds, worse in reverse.",
      diagnosis:
        "RF inner pad worn to 2 mm with heat checking on the rotor. LF pads at 4 mm. Recommend RF pads and rotors now; LF pads at next service.",
      techNotes: "FOUND RF INNER PAD 2MM ROTOR HEAT CRACKED LF 4MM REC RF PADS ROTORS",
      lines: [
        line("l1", "RF brake pads and rotors", 486, 1.5, "recommended"),
        line("l2", "Brake fluid exchange", 189, 0.8, "recommended"),
        line("l3", "Multi-point inspection", 0, 0.3, "approved"),
      ],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -96),
      nextUpdateDue: iso(now, -20),
      notes: "Customer is in the waiting room. Wants to know if she can keep the car today.",
      transportation: "waiting",
      promiseTime: iso(now, 22),
      createdAt: iso(now, -215),
      timeline: [
        ev("t1", -215, now, "Customer checked in", "intake"),
        ev("t2", -198, now, "Assigned to Diego Ruiz", "assign"),
        ev("t3", -176, now, "Diagnosis started", "status"),
        ev("t4", -96, now, "Customer contacted — in lobby, waiting on estimate", "contact"),
        ev("t5", -38, now, "Recommendations entered — waiting for approval", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045282",
      roNumber: "45282",
      customerName: "David Chen",
      customerPhone: "9135550188",
      vehicle: "RAV4 XLE",
      year: 2022,
      mileage: 41210,
      vin: "2T3P1RFV5NW184221",
      technician: "Priya Shah",
      advisor,
      appointmentTime: iso(now, -180),
      status: "waiting_parts",
      statusChangedAt: iso(now, -54),
      concern: "Customer states the A/C blows warm on the highway after 20 minutes.",
      diagnosis: "Leak at the condenser inlet. Condenser ordered; ETA 3:30 p.m. from the PDC.",
      techNotes: "UV DYE CONDENSER INLET WEEP REC CONDENSER 88460-0R030",
      lines: [
        line("l1", "A/C condenser and recharge", 890, 2.2, "approved"),
        line("l2", "Cabin filter", 68, 0.3, "declined"),
      ],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -50),
      nextUpdateDue: iso(now, 40),
      notes: "On a shuttle. Text when the condenser lands.",
      transportation: "shuttle",
      promiseTime: iso(now, 165),
      createdAt: iso(now, -180),
      timeline: [
        ev("t1", -180, now, "Checked in — shuttle requested", "intake"),
        ev("t2", -120, now, "Diagnosis complete", "status"),
        ev("t3", -110, now, "Customer approved condenser via text", "approval"),
        ev("t4", -54, now, "Parts ordered — waiting", "parts"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045283",
      roNumber: "45283",
      customerName: "Marcus Webb",
      customerPhone: "8165550110",
      vehicle: "Tacoma TRD",
      year: 2020,
      mileage: 89340,
      vin: "3TMCZ5AN5LM089334",
      technician: "Marcus Hale",
      advisor,
      appointmentTime: iso(now, -90),
      status: "diagnosing",
      statusChangedAt: iso(now, -48),
      concern: "Customer states a misfire on cold start, MIL on this morning.",
      diagnosis: "",
      techNotes: "P0304 IN PROGRESS SWAP COIL PENDING",
      lines: [line("l1", "Multi-point inspection", 0, 0.3, "approved")],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -88),
      nextUpdateDue: iso(now, 2),
      notes: "Loaner out. Customer at work until 5.",
      transportation: "loaner",
      promiseTime: iso(now, 140),
      createdAt: iso(now, -90),
      timeline: [
        ev("t1", -90, now, "Checked in — loaner 221", "intake"),
        ev("t2", -48, now, "Assigned to Marcus Hale — diagnosing", "assign"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045284",
      roNumber: "45284",
      customerName: "Priya Nair",
      customerPhone: "9135550162",
      vehicle: "Highlander Limited",
      year: 2023,
      mileage: 22180,
      vin: "5TDGZRBH8PS145218",
      technician: "Jordan Blake",
      advisor,
      appointmentTime: iso(now, -40),
      status: "waiting_technician",
      statusChangedAt: iso(now, -28),
      concern: "Customer states a rattle from the rear over bumps, started after last oil service.",
      diagnosis: "",
      techNotes: "",
      lines: [line("l1", "Multi-point inspection", 0, 0.3, "approved")],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -36),
      nextUpdateDue: iso(now, 54),
      notes: "Drop-off. Keys in slot 14.",
      transportation: "dropoff",
      promiseTime: iso(now, 200),
      createdAt: iso(now, -40),
      timeline: [
        ev("t1", -40, now, "Drop-off check-in", "intake"),
        ev("t2", -28, now, "Waiting for a technician", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045285",
      roNumber: "45285",
      customerName: "Helen Brooks",
      customerPhone: "8165550194",
      vehicle: "Corolla LE",
      year: 2019,
      mileage: 104220,
      vin: "JTDEPRAE4KJ028441",
      technician: "Chris Nguyen",
      advisor,
      appointmentTime: iso(now, -260),
      status: "repair_in_progress",
      statusChangedAt: iso(now, -70),
      concern: "Customer states the car will not pass inspection — rusted brake lines mentioned by last shop.",
      diagnosis: "RF brake hose weeping. Both front hoses recommended; RF required to close the RO.",
      techNotes: "RF HOSE WEEP LF SURFACE RUST REC BOTH FRONT HOSES",
      lines: [
        line("l1", "RF brake hose", 312, 1.0, "approved"),
        line("l2", "LF brake hose", 312, 1.0, "declined"),
        line("l3", "Brake fluid exchange", 189, 0.8, "approved"),
      ],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -80),
      nextUpdateDue: iso(now, 10),
      notes: "Declined LF hose. Documented. Waiting-room customer left for lunch.",
      transportation: "waiting",
      promiseTime: iso(now, 55),
      createdAt: iso(now, -260),
      timeline: [
        ev("t1", -260, now, "Checked in", "intake"),
        ev("t2", -200, now, "Estimate presented", "contact"),
        ev("t3", -190, now, "Approved RF hose, declined LF", "approval"),
        ev("t4", -70, now, "Repair in progress", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045286",
      roNumber: "45286",
      customerName: "James Okafor",
      customerPhone: "9135550127",
      vehicle: "Tundra 1794",
      year: 2024,
      mileage: 12840,
      vin: "5TFJA5DB3RX048612",
      technician: "Diego Ruiz",
      advisor,
      appointmentTime: iso(now, -310),
      status: "ready_for_pickup",
      statusChangedAt: iso(now, -18),
      concern: "Customer states a 5,000-mile service and a chip in the windshield.",
      diagnosis: "Completed factory 5k. Windshield chip out of spec for resin — quoted glass, declined.",
      techNotes: "5K DONE CHIP 8MM EDGE DECLINED GLASS",
      lines: [
        line("l1", "5,000-mile service", 289, 1.0, "approved"),
        line("l2", "Cabin filter", 78, 0.2, "approved"),
        line("l3", "Windshield replacement", 1180, 2.0, "declined"),
      ],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -16),
      nextUpdateDue: iso(now, -5),
      notes: "Ready. Customer said he would Uber after 3.",
      transportation: "dropoff",
      promiseTime: iso(now, -10),
      createdAt: iso(now, -310),
      timeline: [
        ev("t1", -310, now, "Checked in", "intake"),
        ev("t2", -40, now, "QC complete", "status"),
        ev("t3", -18, now, "Ready for pickup", "status"),
        ev("t4", -16, now, "Texted customer — ready", "contact"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045287",
      roNumber: "45287",
      customerName: "Sofia Alvarez",
      customerPhone: "8165550155",
      vehicle: "4Runner SR5",
      year: 2018,
      mileage: 118640,
      vin: "JTEBU5JR5J5614410",
      technician: "Priya Shah",
      advisor,
      appointmentTime: iso(now, -75),
      status: "recommendations_ready",
      statusChangedAt: iso(now, -12),
      concern: "Customer states a howl from the rear on the highway around 65 mph.",
      diagnosis: "Rear differential fluid burnt; backlash at spec. Recommend fluid service now. Ring and pinion later if noise remains.",
      techNotes: "RR DIFF FLUID BLACK HOWL 65 REC FLUID SERVICE",
      lines: [
        line("l1", "Rear differential service", 248, 0.8, "recommended"),
        line("l2", "Four-wheel alignment", 169, 1.0, "recommended"),
      ],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -70),
      nextUpdateDue: iso(now, -5),
      notes: "On rental. Call before 3 — she has a meeting.",
      transportation: "rental",
      promiseTime: iso(now, 90),
      createdAt: iso(now, -75),
      timeline: [
        ev("t1", -75, now, "Checked in — rental", "intake"),
        ev("t2", -12, now, "Recommendations ready", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045288",
      roNumber: "45288",
      customerName: "Owen Blake",
      customerPhone: "9135550103",
      vehicle: "Camry Hybrid",
      year: 2022,
      mileage: 35610,
      vin: "4T1C11AK5NU569102",
      technician: "Unassigned",
      advisor,
      appointmentTime: iso(now, -12),
      status: "checked_in",
      statusChangedAt: iso(now, -8),
      concern: "Customer states the car was in for a campaign last month and the dash camera still throws a USB error.",
      diagnosis: "",
      techNotes: "",
      lines: [line("l1", "Multi-point inspection", 0, 0.3, "approved")],
      contactPref: "text",
      lastCustomerUpdate: null,
      nextUpdateDue: iso(now, 17),
      notes: "Waiting in the lobby with kids.",
      transportation: "waiting",
      promiseTime: iso(now, 75),
      createdAt: iso(now, -12),
      timeline: [ev("t1", -12, now, "Checked in — waiting", "intake")],
    },
    {
      id: "00000000-0000-4000-8000-000000045289",
      roNumber: "45289",
      customerName: "Nina Patel",
      customerPhone: "8165550177",
      vehicle: "Sienna XSE",
      year: 2021,
      mileage: 54880,
      vin: "5TDKRKEC2MS041228",
      technician: "Jordan Blake",
      advisor,
      appointmentTime: iso(now, -150),
      status: "waiting_video",
      statusChangedAt: iso(now, -22),
      concern: "Customer states a clunk from the front when turning from a stop.",
      diagnosis: "",
      techNotes: "LF LOWER ARM BUSH PLAY VIDEO PENDING",
      lines: [line("l1", "Multi-point inspection", 0, 0.3, "approved")],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -140),
      nextUpdateDue: iso(now, 5),
      notes: "Wants a video before she approves anything.",
      transportation: "dropoff",
      promiseTime: iso(now, 110),
      createdAt: iso(now, -150),
      timeline: [
        ev("t1", -150, now, "Checked in", "intake"),
        ev("t2", -22, now, "Tech requested video for customer", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045290",
      roNumber: "45290",
      customerName: "Chris Nguyen",
      customerPhone: "9135550199",
      vehicle: "Lexus RX 350",
      year: 2020,
      mileage: 61240,
      vin: "2T2ZZMCA5LC161209",
      technician: "Chris Nguyen",
      advisor,
      appointmentTime: iso(now, -240),
      status: "quality_check",
      statusChangedAt: iso(now, -15),
      concern: "Customer states the sunroof drain is leaking onto the headliner after rain.",
      diagnosis: "Drains cleared. Headliner spot — customer declined trim; water test passed.",
      techNotes: "DRAINS CLEAR WATER TEST PASS HEADLINER SPOT DECLINED",
      lines: [
        line("l1", "Sunroof drain service", 186, 0.8, "approved"),
        line("l2", "Headliner evaluation", 0, 0.4, "approved"),
      ],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -90),
      nextUpdateDue: iso(now, 0),
      notes: "QC then call. Customer at the office.",
      transportation: "loaner",
      promiseTime: iso(now, 35),
      createdAt: iso(now, -240),
      timeline: [
        ev("t1", -240, now, "Checked in — loaner", "intake"),
        ev("t2", -90, now, "Update — drains clear, water test next", "contact"),
        ev("t3", -15, now, "In quality check", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045291",
      roNumber: "45291",
      customerName: "Ruth Klein",
      customerPhone: "8165550131",
      vehicle: "RAV4 Prime",
      year: 2023,
      mileage: 18770,
      vin: "JTMEB3FV6PD123901",
      technician: "Priya Shah",
      advisor,
      appointmentTime: iso(now, -55),
      status: "approved",
      statusChangedAt: iso(now, -9),
      concern: "Customer states a 10,000-mile service and a squeak from the brake pedal.",
      diagnosis: "Pedal hinge dry. Service plus pedal lube. Rear pads at 6 mm — recommend next visit.",
      techNotes: "PEDAL HINGE DRY 10K DONE RR PADS 6MM",
      lines: [
        line("l1", "10,000-mile service", 329, 1.2, "approved"),
        line("l2", "Brake pedal lube", 0, 0.2, "approved"),
      ],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -11),
      nextUpdateDue: iso(now, 79),
      notes: "Approved via text. Put in next open bay.",
      transportation: "waiting",
      promiseTime: iso(now, 50),
      createdAt: iso(now, -55),
      timeline: [
        ev("t1", -55, now, "Checked in — waiting", "intake"),
        ev("t2", -11, now, "Texted estimate — approved", "approval"),
        ev("t3", -9, now, "Approved — waiting on a bay", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045292",
      roNumber: "45292",
      customerName: "Andre Lewis",
      customerPhone: "9135550148",
      vehicle: "Highlander Hybrid",
      year: 2019,
      mileage: 97210,
      vin: "5TDDZRBH5KS164430",
      technician: "Marcus Hale",
      advisor,
      appointmentTime: iso(now, -400),
      status: "waiting_parts",
      statusChangedAt: iso(now, -210),
      concern: "Customer states a hybrid system warning and reduced power on the on-ramp.",
      diagnosis: "Inverter coolant pump seized. Pump on national backorder — ETA tomorrow 10 a.m.",
      techNotes: "INV PUMP SEIZED 10845-0R010 BACKORDER ETA TOM 10A",
      lines: [line("l1", "Inverter coolant pump", 1240, 2.4, "approved")],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -200),
      nextUpdateDue: iso(now, -80),
      notes: "Extended warranty pending. Call the carrier if the pump slips.",
      transportation: "loaner",
      promiseTime: iso(now, 60 * 18),
      createdAt: iso(now, -400),
      timeline: [
        ev("t1", -400, now, "Checked in — towed", "intake"),
        ev("t2", -280, now, "Diagnosis complete", "status"),
        ev("t3", -260, now, "Customer approved pump", "approval"),
        ev("t4", -210, now, "Parts on backorder", "parts"),
        ev("t5", -200, now, "Called — loaner kept overnight", "contact"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045270",
      roNumber: "45270",
      customerName: "Maya Ortiz",
      customerPhone: "8165550108",
      vehicle: "Camry LE",
      year: 2018,
      mileage: 121440,
      vin: "4T1B11HK5JU567210",
      technician: "Diego Ruiz",
      advisor,
      appointmentTime: iso(now, -500),
      status: "completed",
      statusChangedAt: iso(now, -80),
      concern: "Customer states an oil change and rotate.",
      diagnosis: "Completed. Rear tires 4/32 — advised.",
      techNotes: "OC ROTATE RR 4/32 ADVISED",
      lines: [line("l1", "Oil change and rotate", 89, 0.5, "approved")],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -78),
      nextUpdateDue: null,
      notes: "Picked up 1:20 p.m.",
      transportation: "waiting",
      promiseTime: iso(now, -90),
      createdAt: iso(now, -500),
      timeline: [
        ev("t1", -500, now, "Checked in", "intake"),
        ev("t2", -80, now, "Closed — customer paid", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045271",
      roNumber: "45271",
      customerName: "Cole Brennan",
      customerPhone: "9135550150",
      vehicle: "Tacoma SR5",
      year: 2021,
      mileage: 44810,
      vin: "3TMCZ5AN8MM062118",
      technician: "Jordan Blake",
      advisor,
      appointmentTime: iso(now, -430),
      status: "completed",
      statusChangedAt: iso(now, -40),
      concern: "Customer states a recall for the fuel pump.",
      diagnosis: "Campaign complete.",
      techNotes: "22TA02 DONE",
      lines: [line("l1", "Fuel pump campaign", 0, 1.4, "approved")],
      contactPref: "call",
      lastCustomerUpdate: iso(now, -38),
      nextUpdateDue: null,
      notes: "Closed.",
      transportation: "dropoff",
      promiseTime: iso(now, -60),
      createdAt: iso(now, -430),
      timeline: [
        ev("t1", -430, now, "Checked in", "intake"),
        ev("t2", -40, now, "Closed", "status"),
      ],
    },
    {
      id: "00000000-0000-4000-8000-000000045272",
      roNumber: "45272",
      customerName: "Elena Cho",
      customerPhone: "8165550122",
      vehicle: "Corolla Cross",
      year: 2024,
      mileage: 6120,
      vin: "7MUDAABG4RV014882",
      technician: "Chris Nguyen",
      advisor,
      appointmentTime: iso(now, -360),
      status: "completed",
      statusChangedAt: iso(now, -25),
      concern: "Customer states a 5,000-mile service.",
      diagnosis: "Completed.",
      techNotes: "5K DONE",
      lines: [line("l1", "5,000-mile service", 219, 0.8, "approved")],
      contactPref: "text",
      lastCustomerUpdate: iso(now, -24),
      nextUpdateDue: null,
      notes: "Closed.",
      transportation: "waiting",
      promiseTime: iso(now, -30),
      createdAt: iso(now, -360),
      timeline: [
        ev("t1", -360, now, "Checked in", "intake"),
        ev("t2", -25, now, "Closed", "status"),
      ],
    },
  ];
}
