export const LANE_UI_URI = "ui://toyota-dashboard/service-lane.html";

export const laneUiHtml = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font:14px system-ui,sans-serif}body{margin:0;padding:16px;background:#f7f6f2;color:#17201d}header{display:flex;justify-content:space-between;align-items:end;gap:12px}h1{font-size:18px;margin:0}h2{font-size:15px;margin:0 0 10px}p{margin:4px 0;color:#68736f}.tabs{display:flex;gap:6px;margin:14px 0}.tabs button,.primary,button{border:1px solid #cfd8d2;border-radius:8px;background:#fff;color:inherit;padding:7px 10px;cursor:pointer}.tabs button.active,.primary{background:#1f6b4f;color:#fff;border-color:#1f6b4f}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:16px 0}.metric,.card{background:#fff;border:1px solid #dfe3df;border-radius:12px;padding:12px}.metric strong{display:block;font-size:22px}.metric span{font-size:11px;color:#68736f}.list{display:grid;gap:8px}.ro{display:flex;justify-content:space-between;gap:10px;align-items:center;border-bottom:1px solid #edf0ed;padding:8px 0}.ro:last-child{border-bottom:0}.ro button{border:0;background:transparent;text-align:left;padding:0;cursor:pointer;color:inherit}.pill{font-size:11px;padding:3px 7px;border-radius:99px;background:#e5efe9}.empty{padding:24px;text-align:center;color:#68736f}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{display:grid;gap:4px;font-size:12px;color:#68736f}.field input,.field textarea,.field select{box-sizing:border-box;width:100%;border:1px solid #cfd8d2;border-radius:7px;padding:8px;background:#fff;color:#17201d;font:inherit}.full{grid-column:1/-1}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.danger{border-color:#c46b5d;background:#fff1ef}.muted{color:#68736f;font-size:12px}.hidden{display:none!important}.section{margin-top:12px}.detail-head{display:flex;justify-content:space-between;gap:12px;align-items:start}.item{padding:8px 0;border-bottom:1px solid #edf0ed}@media(max-width:520px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>Toyota service lane</h1><p id="subtitle">Ask ChatGPT to show the lane.</p></div><button id="refresh">Refresh</button></header>
<nav class="tabs"><button id="overview-tab" class="active">Overview</button><button id="create-tab">Create RO</button></nav>
<main id="overview"><section class="metrics" id="metrics"></section><section class="card"><div class="list" id="list"><div class="empty">Waiting for lane data…</div></div></section></main>
<main id="create" class="card hidden"><h2>Create repair order</h2><p class="muted">Creates an RO in Toyota Dashboard. No external DMS action is performed.</p><form id="create-form" class="grid"><label class="field">RO number<input name="ro_number" required maxlength="40"></label><label class="field">Customer<input name="customer_name" required maxlength="200"></label><label class="field">Vehicle model<input name="model" required maxlength="120" value="Toyota RAV4"></label><label class="field">Year<input name="year" type="number" min="1900" max="2200"></label><label class="field">Mileage<input name="mileage" type="number" min="0"></label><label class="field">Promise time<input name="promise_at" type="datetime-local"></label><label class="field full">Concern<textarea name="concern" rows="2" maxlength="4000"></textarea></label><label class="field full">Notes<textarea name="notes" rows="2" maxlength="4000"></textarea></label><div class="actions full"><button class="primary" type="submit">Create repair order</button><span id="create-status" class="muted"></span></div></form></main>
<main id="detail" class="card hidden"><div id="detail-content"></div><section id="detail-actions" class="section hidden"><h2>Confirm action</h2><form id="status-form" class="grid"><label class="field">Change status<select name="status"><option value="dispatched">Dispatched</option><option value="diagnosing">Diagnosing</option><option value="estimate_ready">Estimate ready</option><option value="awaiting_approval">Awaiting approval</option><option value="approved">Approved</option><option value="repairing">Repairing</option><option value="qc">Quality check</option><option value="ready">Ready for pickup</option></select></label><div class="actions"><button class="primary" type="submit">Confirm status change</button></div></form><form id="note-form" class="grid section"><label class="field full">Add internal note<textarea name="note" rows="2" required maxlength="4000"></textarea></label><div class="actions full"><button type="submit">Confirm note</button></div></form><div class="actions"><button id="close-ro" class="danger" type="button">Confirm close RO</button><button id="back-overview" type="button">Back to overview</button></div><p id="action-status" class="muted"></p></section></main>
<script>
const state={};const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function unwrap(result){try{return JSON.parse(result?.structuredContent?JSON.stringify(result.structuredContent):result?.content?.find(x=>x.type==='text')?.text||'{}')}catch{return {error:'Invalid tool result'}}}
function show(view){['overview','create','detail'].forEach(id=>$(id).classList.toggle('hidden',id!==view));['overview-tab','create-tab'].forEach(id=>$(id).classList.remove('active'));if(view==='overview')$('overview-tab').classList.add('active');if(view==='create')$('create-tab').classList.add('active')}
function call(name,args,onDone){if(!window.openai?.callTool){$('subtitle').textContent='Host tool bridge unavailable; run this action conversationally.';return}window.openai.callTool(name,args).then(result=>{const data=unwrap(result);if(result?.isError||data?.error){$('action-status').textContent=data.error||result.content?.[0]?.text||'Action failed';return}if(onDone)onDone(data);else render(data)}).catch(()=>{$('action-status').textContent='Action failed; no change was confirmed.'})}
function render(data){if(!data)return;if(data.status&&data.roId){renderDetail(data);return}const counts=data.counts||{};const metrics=[['Active ROs',data.activeCount||0],['Waiting',counts.waiting||0],['Blocked',data.blockedCount||0],['Follow-ups due',data.overdueFollowUpCount||0]];$('metrics').innerHTML=metrics.map(x=>'<div class="metric"><strong>'+esc(x[1])+'</strong><span>'+x[0]+'</span></div>').join('');$('subtitle').textContent=(data.needsAttention?.length||0)+' ROs need attention';const rows=data.repairOrders||data.needsAttention||[];$('list').innerHTML=rows.length?rows.map(r=>'<div class="ro"><button data-ro="'+esc(r.roId||r.roNumber)+'"><strong>RO '+esc(r.roNumber)+'</strong><br><small>'+esc(r.customer||r.vehicle||r.action||'')+'</small></button><span class="pill">'+esc(r.state||r.urgency||'attention')+'</span></div>').join(''):'<div class="empty">No repair orders in this view.</div>';$('list').querySelectorAll('[data-ro]').forEach(button=>button.onclick=()=>call('get_repair_order',{ro_id:button.dataset.ro},renderDetail))}
function renderDetail(data){state.detail=data;show('detail');$('detail-actions').classList.remove('hidden');$('subtitle').textContent='RO '+(data.roNumber||'')+' detail';const operational=data.operational||{};const recommendations=data.recommendations||[];const blockers=data.blockers||[];$('detail-content').innerHTML='<div class="detail-head"><div><h2>RO '+esc(data.roNumber)+'</h2><p>'+esc(data.customer)+' · '+esc(data.vehicle)+'</p></div><span class="pill">'+esc(data.status?.state)+'</span></div><div class="section"><p><strong>Concern:</strong> '+esc(operational.concern||'Not recorded')+'</p><p><strong>Promise:</strong> '+esc(data.status?.promiseAt||'Not set')+'</p><p><strong>Version:</strong> '+esc(data.version)+'</p></div><div class="section"><h2>Recommendations</h2>'+(recommendations.length?recommendations.map(r=>'<div class="item">'+esc(r.description)+' · $'+esc(r.amount)+' · '+esc(r.state)+'</div>').join(''):'<p class="muted">None</p>')+'</div><div class="section"><h2>Active blockers</h2>'+(blockers.length?blockers.map(b=>'<div class="item">'+esc(b.type)+' · '+esc(b.description)+'</div>').join(''):'<p class="muted">None</p>')+'</div>';$('status-form').status.value=data.status?.state||'dispatched'}
function refresh(){call('get_lane_summary',{},data=>{show('overview');render(data)})}
$('overview-tab').onclick=()=>{show('overview');refresh()};$('create-tab').onclick=()=>show('create');$('refresh').onclick=refresh;$('back-overview').onclick=()=>{show('overview');refresh()};
$('create-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target);const args={ro_number:form.get('ro_number'),customer_name:form.get('customer_name'),model:form.get('model'),concern:form.get('concern')||undefined,notes:form.get('notes')||undefined};if(form.get('year'))args.year=Number(form.get('year'));if(form.get('mileage'))args.mileage=Number(form.get('mileage'));if(form.get('promise_at'))args.promise_at=new Date(form.get('promise_at')).toISOString();$('create-status').textContent='Awaiting confirmation…';call('create_repair_order',args,data=>{$('create-status').textContent='Created RO '+data.roNumber;call('get_repair_order',{ro_id:data.roId},renderDetail)})};
$('status-form').onsubmit=e=>{e.preventDefault();if(!state.detail)return;const form=new FormData(e.target);$('action-status').textContent='Awaiting confirmation…';call('update_repair_order_status',{repair_order_id:state.detail.roId,status:form.get('status'),expected_version:state.detail.version},data=>{call('get_repair_order',{ro_id:state.detail.roId},renderDetail)})};
$('note-form').onsubmit=e=>{e.preventDefault();if(!state.detail)return;const form=new FormData(e.target);call('update_repair_order_notes',{repair_order_id:state.detail.roId,note:form.get('note')},()=>{$('action-status').textContent='Note recorded.';e.target.reset()})};
$('close-ro').onclick=()=>{if(!state.detail)return;$('action-status').textContent='Awaiting close confirmation…';call('close_repair_order',{repair_order_id:state.detail.roId,expected_version:state.detail.version},data=>{$('action-status').textContent='RO closed as '+data.status;call('get_repair_order',{ro_id:state.detail.roId},renderDetail)})};window.addEventListener('message',event=>{const message=event.data;if(message?.method==='ui/notifications/tool-result')render(unwrap(message.params?.result));if(message?.method==='ui/notifications/structuredContent')render(message.params)});
</script></body></html>`;
