/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppDriversRouteImport } from './routes/_app/drivers'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppFuelRouteImport } from './routes/_app/fuel'
import { Route as AppMaintenanceRouteImport } from './routes/_app/maintenance'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppRosRouteImport } from './routes/_app/ros'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppVehiclesRouteImport } from './routes/_app/vehicles'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppFleetIndexRouteImport } from './routes/_app/fleet/index'
import { Route as AppFleetAlertsRouteImport } from './routes/_app/fleet/alerts'
import { Route as AppFleetDriversRouteImport } from './routes/_app/fleet/drivers'
import { Route as AppFleetFuelRouteImport } from './routes/_app/fleet/fuel'
import { Route as AppFleetMaintenanceRouteImport } from './routes/_app/fleet/maintenance'
import { Route as AppFleetSettingsRouteImport } from './routes/_app/fleet/settings'
import { Route as AppFleetVehiclesRouteImport } from './routes/_app/fleet/vehicles'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInternalGrokRegistrationRouteImport } from './routes/api/internal/grok-registration'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppFuelRoute = AppFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppRosRoute = AppRosRouteImport.update({
  id: '/ros',
  path: '/ros',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFleetIndexRoute = AppFleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetAlertsRoute = AppFleetAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetDriversRoute = AppFleetDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetFuelRoute = AppFleetFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetMaintenanceRoute = AppFleetMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetSettingsRoute = AppFleetSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppFleetRoute,
} as any)
const AppFleetVehiclesRoute = AppFleetVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppFleetRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalGrokRegistrationRoute =
  ApiInternalGrokRegistrationRouteImport.update({
    id: '/api/internal/grok-registration',
    path: '/api/internal/grok-registration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/drivers': typeof AppDriversRoute
  '/fleet': typeof AppFleetRouteWithChildren
  '/follow-ups': typeof AppFollowUpsRoute
  '/fuel': typeof AppFuelRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/notes': typeof AppNotesRoute
  '/performance': typeof AppPerformanceRoute
  '/ros': typeof AppRosRoute
  '/settings': typeof AppSettingsRoute
  '/vehicles': typeof AppVehiclesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/fleet/alerts': typeof AppFleetAlertsRoute
  '/fleet/drivers': typeof AppFleetDriversRoute
  '/fleet/fuel': typeof AppFleetFuelRoute
  '/fleet/maintenance': typeof AppFleetMaintenanceRoute
  '/fleet/settings': typeof AppFleetSettingsRoute
  '/fleet/vehicles': typeof AppFleetVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/grok-registration': typeof ApiInternalGrokRegistrationRoute
  '/fleet/': typeof AppFleetIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/drivers': typeof AppDriversRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/fuel': typeof AppFuelRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/notes': typeof AppNotesRoute
  '/performance': typeof AppPerformanceRoute
  '/ros': typeof AppRosRoute
  '/settings': typeof AppSettingsRoute
  '/vehicles': typeof AppVehiclesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/': typeof AppIndexRoute
  '/fleet/alerts': typeof AppFleetAlertsRoute
  '/fleet/drivers': typeof AppFleetDriversRoute
  '/fleet/fuel': typeof AppFleetFuelRoute
  '/fleet/maintenance': typeof AppFleetMaintenanceRoute
  '/fleet/settings': typeof AppFleetSettingsRoute
  '/fleet/vehicles': typeof AppFleetVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/grok-registration': typeof ApiInternalGrokRegistrationRoute
  '/fleet': typeof AppFleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/fleet': typeof AppFleetRouteWithChildren
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/fuel': typeof AppFuelRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/ros': typeof AppRosRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/fleet/alerts': typeof AppFleetAlertsRoute
  '/_app/fleet/drivers': typeof AppFleetDriversRoute
  '/_app/fleet/fuel': typeof AppFleetFuelRoute
  '/_app/fleet/maintenance': typeof AppFleetMaintenanceRoute
  '/_app/fleet/settings': typeof AppFleetSettingsRoute
  '/_app/fleet/vehicles': typeof AppFleetVehiclesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/grok-registration': typeof ApiInternalGrokRegistrationRoute
  '/_app/fleet/': typeof AppFleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/consent'
    | '/login'
    | '/alerts'
    | '/drivers'
    | '/fleet'
    | '/follow-ups'
    | '/fuel'
    | '/maintenance'
    | '/notes'
    | '/performance'
    | '/ros'
    | '/settings'
    | '/vehicles'
    | '/api/mcp'
    | '/fleet/alerts'
    | '/fleet/drivers'
    | '/fleet/fuel'
    | '/fleet/maintenance'
    | '/fleet/settings'
    | '/fleet/vehicles'
    | '/api/auth/$'
    | '/api/internal/grok-registration'
    | '/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/consent'
    | '/login'
    | '/alerts'
    | '/drivers'
    | '/follow-ups'
    | '/fuel'
    | '/maintenance'
    | '/notes'
    | '/performance'
    | '/ros'
    | '/settings'
    | '/vehicles'
    | '/api/mcp'
    | '/'
    | '/fleet/alerts'
    | '/fleet/drivers'
    | '/fleet/fuel'
    | '/fleet/maintenance'
    | '/fleet/settings'
    | '/fleet/vehicles'
    | '/api/auth/$'
    | '/api/internal/grok-registration'
    | '/fleet'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/consent'
    | '/login'
    | '/_app/alerts'
    | '/_app/drivers'
    | '/_app/fleet'
    | '/_app/follow-ups'
    | '/_app/fuel'
    | '/_app/maintenance'
    | '/_app/notes'
    | '/_app/performance'
    | '/_app/ros'
    | '/_app/settings'
    | '/_app/vehicles'
    | '/api/mcp'
    | '/_app/'
    | '/_app/fleet/alerts'
    | '/_app/fleet/drivers'
    | '/_app/fleet/fuel'
    | '/_app/fleet/maintenance'
    | '/_app/fleet/settings'
    | '/_app/fleet/vehicles'
    | '/api/auth/$'
    | '/api/internal/grok-registration'
    | '/_app/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalGrokRegistrationRoute: typeof ApiInternalGrokRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fuel': {
      id: '/_app/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof AppFuelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ros': {
      id: '/_app/ros'
      path: '/ros'
      fullPath: '/ros'
      preLoaderRoute: typeof AppRosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fleet/': {
      id: '/_app/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AppFleetIndexRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/alerts': {
      id: '/_app/fleet/alerts'
      path: '/alerts'
      fullPath: '/fleet/alerts'
      preLoaderRoute: typeof AppFleetAlertsRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/drivers': {
      id: '/_app/fleet/drivers'
      path: '/drivers'
      fullPath: '/fleet/drivers'
      preLoaderRoute: typeof AppFleetDriversRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/fuel': {
      id: '/_app/fleet/fuel'
      path: '/fuel'
      fullPath: '/fleet/fuel'
      preLoaderRoute: typeof AppFleetFuelRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/maintenance': {
      id: '/_app/fleet/maintenance'
      path: '/maintenance'
      fullPath: '/fleet/maintenance'
      preLoaderRoute: typeof AppFleetMaintenanceRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/settings': {
      id: '/_app/fleet/settings'
      path: '/settings'
      fullPath: '/fleet/settings'
      preLoaderRoute: typeof AppFleetSettingsRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/_app/fleet/vehicles': {
      id: '/_app/fleet/vehicles'
      path: '/vehicles'
      fullPath: '/fleet/vehicles'
      preLoaderRoute: typeof AppFleetVehiclesRouteImport
      parentRoute: typeof AppFleetRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/grok-registration': {
      id: '/api/internal/grok-registration'
      path: '/api/internal/grok-registration'
      fullPath: '/api/internal/grok-registration'
      preLoaderRoute: typeof ApiInternalGrokRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFleetRouteChildren {
  AppFleetAlertsRoute: typeof AppFleetAlertsRoute
  AppFleetDriversRoute: typeof AppFleetDriversRoute
  AppFleetFuelRoute: typeof AppFleetFuelRoute
  AppFleetMaintenanceRoute: typeof AppFleetMaintenanceRoute
  AppFleetSettingsRoute: typeof AppFleetSettingsRoute
  AppFleetVehiclesRoute: typeof AppFleetVehiclesRoute
  AppFleetIndexRoute: typeof AppFleetIndexRoute
}

const AppFleetRouteChildren: AppFleetRouteChildren = {
  AppFleetAlertsRoute: AppFleetAlertsRoute,
  AppFleetDriversRoute: AppFleetDriversRoute,
  AppFleetFuelRoute: AppFleetFuelRoute,
  AppFleetMaintenanceRoute: AppFleetMaintenanceRoute,
  AppFleetSettingsRoute: AppFleetSettingsRoute,
  AppFleetVehiclesRoute: AppFleetVehiclesRoute,
  AppFleetIndexRoute: AppFleetIndexRoute,
}

const AppFleetRouteWithChildren = AppFleetRoute._addFileChildren(
  AppFleetRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDriversRoute: typeof AppDriversRoute
  AppFleetRoute: typeof AppFleetRouteWithChildren
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppFuelRoute: typeof AppFuelRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppRosRoute: typeof AppRosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDriversRoute: AppDriversRoute,
  AppFleetRoute: AppFleetRouteWithChildren,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppFuelRoute: AppFuelRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppNotesRoute: AppNotesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppRosRoute: AppRosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalGrokRegistrationRoute: ApiInternalGrokRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
